name: homepage

services:
  homepage:
    image: gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped

    user: "1000:1000"

    group_add:
      - "989"

    env_file:
      - ./config/.env

    environment:
      HOMEPAGE_ALLOWED_HOSTS: ${HOMEPAGE_ALLOWED_HOSTS}
      PUID: 1000
      PGID: 1000
      UMASK: "022"

    volumes:
      - ./config:/app/config
      - /mnt/media:/mnt/media:ro
      - /home:/home:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/icons:/app/public/icons
      - ./config/custom:/app/public/custom

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.homepage.rule=Host(`dash.maadmustafa.dev`)"
      - "traefik.http.routers.homepage.entrypoints=websecure"
      - "traefik.http.routers.homepage.tls=true"
      - "traefik.http.routers.homepage.tls.certresolver=cloudflare"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"

    networks:
      - proxy
      - admin

networks:
  proxy:
    external: true
  admin:
    external: true