services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - "${HOMEPAGE_HTTP_PORTS}"
    volumes:
      - ./config:/app/config
      - /mnt/media:/mnt/media:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/icons:/app/public/icons
    environment:
      HOMEPAGE_ALLOWED_HOSTS: ${HOMEPAGE_ALLOWED_HOSTS}
    networks:
      - shared_net
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: "true"

networks:
  shared_net:
    external: true
