- Work:
  - ChatGPT:
     - icon: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/chatgpt-light.webp
       href: "{{HOMEPAGE_VAR_BOOKMARK_WORK_CHATGPT_URL}}"
  - Work gmail:
     - icon: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/gmail.webp
       href: "{{HOMEPAGE_VAR_BOOKMARK_WORK_GMAIL_URL}}"
  - GitHub:
     - icon: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/github-light.webp
       href: "{{HOMEPAGE_VAR_BOOKMARK_GITHUB_URL}}"
  - Cloudflare:
     - icon: si-cloudflare-#F38020
       href: "{{HOMEPAGE_VAR_BOOKMARK_CLOUDFLARE_URL}}"
  - Cluade:
      - icon: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/claude.webp
        href: "{{HOMEPAGE_VAR_BOOKMARK_WORK_CLAUDE_URL}}"

- Personal:
  - Personal gmail:
     - icon: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/gmail.webp
       href: "{{HOMEPAGE_VAR_BOOKMARK_PERSONAL_GMAIL_URL}}"

- Entertainment:
  - Valorant:
     - icon: si-valorant-#FF4654
       href: "{{HOMEPAGE_VAR_BOOKMARK_VALORANT_URL}}"
  - 1337x:
     - icon: /icons/1337x.webp
       href: "{{HOMEPAGE_VAR_BOOKMARK_1337X_URL}}"
  - YTS:
     - icon: /icons/yts.webp
       href: "{{HOMEPAGE_VAR_BOOKMARK_YTS_URL}}"
  - Pahe.in:
     - icon: /icons/paheink.webp
       href: "{{HOMEPAGE_VAR_BOOKMARK_PAHE_URL}}"