- Work:
  - ChatGPT:
     - icon: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/chatgpt-light.webp
       href: https://chatgpt.com/g/g-p-6870023d1d4881919de4a3e1e3d1fced-maad/project
  - Work gmail:
     - icon: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/gmail.webp
       href: https://mail.google.com/mail/u/1/#inbox
  - GitHub:
     - icon: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/github-light.webp
       href: https://github.com/Nightwalker28
  - Cloudflare:
     - icon: si-cloudflare-#F38020
       href: https://dash.cloudflare.com/b33b89b005a08218713c0d91257dbdc4/home/domains
  - GoDaddy:
     - icon: si-godaddy-#1BDBDB
       href: https://dcc.godaddy.com/control/dnsmanagement

- Personal:
  - Personal gmail:
     - icon: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/gmail.webp
       href: https://mail.google.com/mail/u/0/#inbox

- Entertainment:
  - Valorant:
     - icon: si-valorant-#FF4654
       href: https://valorantesports.com/en-US/leagues/champions,game_changers_championship,vct_americas,vct_emea,vct_masters,vct_pacific
  - AnimePahe:
     - icon: /icons/animepahe.png
       href: https://animepahe.com/
       id: animepahe
  - TodayTv:
     - icon: /icons/todaytv.png
       href: https://www.todaytvseries1.com/
  - 1337x:
     - icon: /icons/1337x.png
       href: https://x1337x.cc/
  - YTS:
     - icon: /icons/yts.png
       href: https://yts.mx/
  - Pahe.in:
     - icon: /icons/paheink.png
       href: https://pahe.ink/