title: WALKER HUB
favicon: /icons/fav.svg
disableCollapse: false
background:
  image: /icons/background.jpg
  blur: xs
  brightness: 51
cardBlur: 4xl
theme: dark
headerStyle: clean
iconStyle: theme
statusStyle: dot
quicklaunch:
  searchDescriptions: true
  mobileButtonPosition: top-right
hideVersion: true
hideErrors: true
fiveColumns: true
useEqualHeights: true
preloadAllWidgets: true
layout:
  Work:
    tab: Home
    iconsOnly: true
  Personal:
    tab: Home
    iconsOnly: true
  Entertainment:
    tab: Home
    iconsOnly: true
  Home:
    header: true
    tab: Home
    style: row
    columns: 4
  Calendar:
    header: true
    tab: Home
    style: row
    columns: 3
  MEDIA:
    header: true
    tab: Media
    style: row
    columns: 3
  ARR:
    header: true
    tab: Media
    style: row
    columns: 4
  MANAGER:
    header: true
    tab: Media
    style: row
    columns: 2
  Infrastructure:
    header: false
    tab: Infrastructure
    style: row
    columns: 4
  PVE-NODE:
    header: true
    tab: Infrastructure
    style: row
    columns: 1
  SPEEDTEST-MONITOR:
    header: true
    tab: Infrastructure
    style: row
    columns: 1
  ADGUARD - CONTROL:
    header: true
    tab: Infrastructure
    style: row
    columns: 1
  Bookmarks:
    header: false
    tab: Bookmarks
    style: row
    columns: 4
