title: Nightwalker's Homepage
favicon: /icons/profile.webp
disableCollapse: false
background:
  image: /icons/wallpaper.webp
  blur: sm
  brightness: 51
cardBlur: 4xl
theme: dark
headerStyle: clean
iconStyle: theme
statusStyle: dot
quicklaunch:
  searchDescriptions: true
hideVersion: true
hideErrors: true
fiveColumns: true
useEqualHeights: true
preloadAllWidgets: true
layout:
  Work:
    tab: Home
    iconsOnly: true
  Personal:
    tab: Home
    iconsOnly: true
  Entertainment:
    tab: Home
    iconsOnly: true
  Home:
    header: false
    tab: Home
    style: row
    columns: 4
  Media:
    header: false
    tab: Media
    style: row
    columns: 4
  Infrastructure:
    header: false
    tab: Infrastructure
    style: row
    columns: 4
  Bookmarks:
    header: false
    tab: Bookmarks
    style: row
    columns: 4