- logo:
    icon: /icons/profile.png
    id: logo

- greeting:
    text_size: xl
    text: Welcome Nightwalker28

- resources:
    label: System
    disk:
      - /

- resources:
    label: Media
    disk:
      - /mnt/media
      
- search:
    id: search
    provider: google

- datetime:
    locale: en
    text_size: sm
    format:
      dateStyle: short
      timeStyle: short
      hour12: true
      timeZone: 'Asia/Colombo'

- openweathermap:
    #label: Colombo, LK
    units: metric
    provider: openweathermap
    apiKey: 'f24d8f411c62ddd73b36b3d6d88a2a45'
    latitude: 6.9271
    longitude: 79.8612
    cache: 10
