- logo:
    icon: /icons/profile.webp

- greeting:
    text_size: xl
    text: "${HOMEPAGE_GREETING_TEXT}"

- resources:
    label: System
    disk:
      - /

- resources:
    label: Media
    disk:
      - /mnt/media
      
- search:
    id: search
    provider: google

- datetime:
    locale: en
    text_size: sm
    format:
      dateStyle: short
      timeStyle: short
      hour12: true
      timeZone: "${HOMEPAGE_TIMEZONE}"

- openweathermap:
    #label: Colombo, LK
    units: metric
    provider: openweathermap
    apiKey: "${HOMEPAGE_OPENWEATHER_API_KEY}"
    latitude: ${HOMEPAGE_OPENWEATHER_LATITUDE}
    longitude: ${HOMEPAGE_OPENWEATHER_LONGITUDE}
    cache: 10
