- logo:
    icon: /icons/profile.webp

- greeting:
    text_size: xl
    text: {{HOMEPAGE_VAR_GREETING_TEXT}}

- resources:
    label: System
    disk:
      - /

- resources:
    label: Appdata
    disk:
      - /home

- resources:
    label: Media
    disk:
      - /mnt/media
      
- search:
    id: search
    provider: duckduckgo
    focus: true

- datetime:
    locale: en
    text_size: sm
    format:
      dateStyle: short
      timeStyle: short
      hour12: true
      timeZone: "{{HOMEPAGE_VAR_TIMEZONE}}"

- openweathermap:
    #label: Colombo, LK
    units: metric
    provider: openweathermap
    apiKey: "{{HOMEPAGE_VAR_OPENWEATHER_API_KEY}}"
    latitude: {{HOMEPAGE_VAR_OPENWEATHER_LATITUDE}}
    longitude: {{HOMEPAGE_VAR_OPENWEATHER_LONGITUDE}}
    cache: 10
